import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/globals.css";
import { GraphQlProvider } from "../components/providers/graphql-provider";
import { ModalProvider } from "../components/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GraphQlProvider>
          <ModalProvider />
          {children}
        </GraphQlProvider>
      </body>
    </html>
  );
}
